### ISSUE TITLE
Big Sur, Broadcom DW1830 Wifi, X250, wifi broken after wake from sleep

### ISSUE THREAD

**Issue by wafflekoan** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#17]
Your guide and OC files work great! I have experience with Clover, but this is my first time with OC. It was pretty flawless and straightforward getting this working for the first time.

However, when I close the lid of my X250 and let the machine go to sleep, upon wake the internet no longer works. The wifi remains connected, and I can turn it off and back on again, it connects, but there is just no internet connection. A reboot fixes it. Wifi card is Broadcom DW1830.

I've tried adding AirportBcrmFixup.kext to my Kext folder, which is a kext I used with Clover on this machine, but it doesn't seem to help. Back on Clover, I had no issues with the Broadcom wifi at all, but that was also on Catalina.

Any idea what it could be? Thanks in advance!

---
OS: Big Sur 11.2.1
Laptop: ThinkPad X250
Wifi: DW1830

**Comment by racka98** [comment]
Hhm I'm not so sure because i don't have Broadcom card.

Install IORegExplorer then search for Bcrm or Broadcom and post the screenshot of all the entries found in there with that name

**Comment by wafflekoan** [comment]
When I run IORegExplorer and search for either Bcrm or Broadcom, nothing comes up.

Do you have any issues personally with your Intel wifi card? I also have the native Intel card (7265) that came with my X250 and I can install and use that if it works. It's just been my experience that Intel wifi and Hackintosh doesn't work well. Has that changed?

**Comment by racka98** [comment]
Possibly the kext is not being fully loaded after wake from sleep. If it's correctly loaded it should show up in IOReg


The Intel card works perfectly. Intel cards are now supported with the help of Openintelwireless kexts. The only issue is with bluetooth, when you connect to bluetooth devices that don't have strong antennas the sound becomes choppy or disconnets.  Sound is choppy on my earbuds but it works perfectly fine on my Bluetooth speaker which has better antennas.

It's a known limitation of the 7260/7265 cards because of the Linux driver used. Also this issue only happens when you are connected to wifi, if you turn off wifi your bluetooth works as it's supposed to.

Other than that i have no issues with WiFi on Big Sur. I almost never shutdown my laptop and only depend on sleep/wake and it has worked perfectly for months now.

**Comment by wafflekoan** [comment]
That's great, thank you. I've installed my Intel 7265 card, speeds are great, and internet works after wake from sleep. I personally don't really use Bluetooth for anything, so that's a non-issue for me. But this seems to be working well. Thanks so much for your quick responses. I appreciate your assistance!

**Comment by racka98** [comment]
No problem.

**Comment by racka98** [comment]
> That's great, thank you. I've installed my Intel 7265 card, speeds are great, and internet works after wake from sleep. I personally don't really use Bluetooth for anything, so that's a non-issue for me. But this seems to be working well. Thanks so much for your quick responses. I appreciate your assistance!

Just make sure you use the Intel kexts in this repo. As I've removed all the unnecessary firmware for other cards that improves kext loading at boot. I usually update them when i update other kexts or update opencore
