### ISSUE TITLE
Big Sur 11.6 auto update

### ISSUE THREAD

**Issue by fearlipe** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#59]
Big Sur 11.6 auto update is working fine or there is issues?

**Comment by fearlipe** [comment]
Anyone update can reply?

**Comment by racka98** [comment]
I have not updated. But I wouldn't recommend it unless you update to a newer version of OpenCore

**Comment by Dynasty-Dev** [comment]
Big sir 11.6 and Monterey beta 6 is working for me but I manually updated to open core 0.7.3 so I’m not sure if it will work for you

**Comment by fearlipe** [comment]
How can I update manually? It work without issues on 11.5.2?

**Comment by Dynasty-Dev** [comment]
Yes,it works perfectly for me. I manually updated by updated the open core files, drivers, kexts and config.plist

**Comment by fearlipe** [comment]
can u send me the open core files link?

**Comment by Dynasty-Dev** [comment]
Do you mean my efi or open core guide where you can update it yourself?

**Comment by fearlipe** [comment]
the guide, unless your efi works with mine. I have the t450 with the intel wifi.

**Comment by Dynasty-Dev** [comment]
Ok, here is the open core guide. https://dortania.github.io/OpenCore-Install-Guide/

**Comment by Dynasty-Dev** [comment]
incase your want to try here is my efi. https://drive.google.com/file/d/1_0HfCZmjAYrQQ7pWEJ-d1K9TzINTLVs9/view?usp=sharing

I added and removed a few things but they easily be added/removed back. I removed yogasmc since I don't usually use the laptop keyboard and I added the boot chime back which was removed by the owner of the repo since someone said it caused issues with sound but I have been using it for months now with no issues whatsoever so maybe its fixed?

**Comment by fearlipe** [comment]
Your link was removed D:

**Comment by Dynasty-Dev** [comment]
Seems like google doesn't support hackintoshing, lol. https://www.filemail.com/d/pwgjfdpukhehiuw

**Comment by fearlipe** [comment]
lmao

**Comment by Dynasty-Dev** [comment]
how is it going?

**Comment by fearlipe** [comment]
Dint tried yet, i'll just finish some work then i'll try.

**Comment by Dynasty-Dev** [comment]
okay

**Comment by Dynasty-Dev** [comment]
How’s it going?
