### ISSUE TITLE
AirDrop not work

### ISSUE THREAD

**Issue by hoangnova** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#6]
Bro, AirDrop not work

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**macOS Info:**
 - OS: [e.g. Big Sur]
 - Version [e.g. 11.0.1]
 - Laptop Model: [e.g. T450 or T450s]

**Additional context**

**Comment by racka98** [comment]
> Bro, AirDrop not work
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **macOS Info:**
>  - OS: [e.g. Big Sur]
>  - Version [e.g. 11.0.1]
>  - Laptop Model: [e.g. T450 or T450s]
> 
> **Additional context**
> Add any other context about the problem here.
> 

You don't have the necessary info in your Bug report. Are you on Catalina or Big Sur? Are you using Airportitlwm or itlwm?

You disabled SecureBootModel so Airportitlwm.kext doesn't work which is the one that supports airdrop

Airdrop also need you to load bluetooth drivers. But since our card has issues on bluetooth I don't know if airdrop will even work with the intel card. I don't have an iPhone so I can't test this

Recommended solution: Replace the card with DW1820A or some other compatible macOS card

**Comment by hoangnova** [comment]
I use on Airportitlwm pro. 
Yep, you right, i disabled SecureBootModel because it cannot boot. 
Tks you
