### ISSUE TITLE
Yoga smc fan 

### ISSUE THREAD

**Issue by Dynasty-Dev** [racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore#63]
Can’t adjust fan speed using yoga smc. Please add this feature into the efi, it already works good without it but I think it’s good to have it because I need it sometimes. Also the yoga smc error pops up each boot which is annoying. Thanks
Sorry for the bad English, I am not from here

**Comment by matyysek** [comment]
Hi, I'm trying to resolve this myself, but with no success. Every time at boot, a windows pops up saying "EC access unavailable! See SSDT-ECRW.dsl". Although I tried, I couldn't work my way around this issue as I'm not that skilled with Hackintoshes. 

Thank you so very much for your work on the repo, installing the Hackintosh was otherwise a piece of cake thanks to you, racka98.

**Comment by racka98** [comment]
I no longer have that laptop so unfortunately I can no longer offer support for this repo
